### ISSUE TITLE
Explain that unprotected quorum/ethereum nodes will be deprecated

### ISSUE THREAD

**Issue by jona-sc** [chainstack/docs#111]
For Quorum and Ethereum, we need to show a warning to explain in the docs that the unprotected endpoints will be deprecated.

**Comment by akegaviar** [comment]
Please update this with the deprecation date when you agree on one.

**Comment by akegaviar** [comment]
Looks like it's October 1.

**Comment by jona-sc** [comment]
Yes, that's right. Forgot to mention in standup.
