### ISSUE TITLE
Missing deprecated APIs information in Release notes of v1.3

### ISSUE THREAD

**Issue by d2phap** [chainstack/docs#146]
## Problems
- In v1.3, we introduced the new endpoints that are protected with basic access authentication for Quorum and Ethereum node that are backwards incompatible API changes and will be deprecating as of October 1, 2019.
- We should mention it in the Release notes as it will impact to all current users (they might read it in the new marketing email `Deprecating legacy endpoints` though).

![image](https://user-images.githubusercontent.com/3154213/65297495-a0c19b00-db9a-11e9-82b9-8da0e999a478.png)

## Expectation 
- Add 1 more section above the `What's New`, call it `Breaking changes` (or whatever), to mention this important information

**Comment by akegaviar** [comment]
@d2phap it's in the very first bullet point:

> Protected endpoints added for Quorum and Ethereum nodes. Read more about the upcoming deprecation of unprotected endpoints

Do you feel we should make it more salient?

(Also thanks for filing this, keep em coming!)

**Comment by d2phap** [comment]
Oh well, so it's not enough outstanding to me.

> we should make it more salient?

I think so!
