### ISSUE TITLE
Warning and Tip blocks default to WARNING and TIP

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#164]
With the latest vuepress update, the warning and tip blocks default to WARNING and TIP.

Compare:

**Option 1:**
![old.png](https://images.zenhubusercontent.com/5cff4f0df743f561805b7654/4eee2e1e-f27a-4936-9cc0-8d6a40dbba8d)

**Option 2:**
![new.png](https://images.zenhubusercontent.com/5cff4f0df743f561805b7654/8b77ac72-bdda-47d3-8fd9-76fd84e6ade8)

I'd like to change that back with no default WARNING and TIP for when no custom title is provided.

**Comment by akegaviar** [comment]
@jona-sc @mcbzz guys what's your opinion on this?

Option 1 — without the default title.
Option 2 — with the default title.

**Comment by jona-sc** [comment]
I say Option 1. The warning title looks a bit severe.
