### ISSUE TITLE
Docs structure with easy item access

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#174]
Think of a docs structure that'd include H3 items in the menu.

**Comment by akegaviar** [comment]
+ @jona-sc

**Comment by jona-sc** [comment]
Not sure if it's easy to do with vuepress but Stripe's 'On this page' section is a nice solution: https://stripe.com/docs/testing#disputes

**Comment by easeev** [comment]
@akegaviar is something like that available for VuePress?

**Comment by easeev** [comment]
>The sidebar automatically displays links for headers in the current active page, nested under the link for the page itself. You can customize this behavior using themeConfig.sidebarDepth. The default depth is 1, which extracts the h2 headers. Setting it to 0 disables the header links, and the max value is 2 which extracts both h2 and h3 headers.

With max depth:

![image.png](https://images.zenhubusercontent.com/5af11d7e4b5806bc2bd22ebf/ea81021f-9579-4e49-9646-6e734685f272)

Better @jona-sc @akegaviar?

**Comment by akegaviar** [comment]
I played around with this and feel like it's better.
