### ISSUE TITLE
Describe network/node states in the docs

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#176]
Reference: [#1334](https://github.com/chainstack/ui/issues/1334).

Update docs to describe what different network/node states mean. 

### Docs update
Add information to docs to describe what each state means exactly:
**Nodes:**
`Pending`
`Running`
`Maintenance`
`Error`
`Failed`

**Networks:**
`Pending`
`Running` with check mark icon (consortium networks)
`Running` with error icon (consortium networks)
`OK` with check mark icon (public chain networks)
`OK` with error icon (public chain networks)
`Failed`

**Could also add CorDapps:**
`Installing`
`Installed`
`Removing`
`Failed`

**Comment by easeev** [comment]
And also in KB
