### ISSUE TITLE
VS Code extension for Hyperledger Fabric

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#188]
Check it out & do instructions

**Comment by akegaviar** [comment]
@CaJIbHuK since you did some testing recently and you are generally in the know with HLF + Chainstack + VS Code IBM extension, can you provide with the latest state of the matter?

Is it something I need to start looking into or not yet?

**Comment by CaJIbHuK** [comment]
What I've tried v2.0.0-beta.7, the latest is v2.0.0-beta.10 (see https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases). So they haven't released it fully :(.

What I've managed to do is:
1) I could connect to nodes by providing json file from ndoe details
![image](https://user-images.githubusercontent.com/18049710/99077918-91878300-25ce-11eb-91b2-80b102375b42.png)
<img width="552" alt="Screenshot 2020-11-13 at 16 38 47" src="https://user-images.githubusercontent.com/18049710/99078995-58e8a900-25d0-11eb-8a8b-79131e5981b7.png">
<img width="743" alt="Screenshot 2020-11-13 at 16 39 38" src="https://user-images.githubusercontent.com/18049710/99079003-5d14c680-25d0-11eb-849d-23f5804a8a92.png">
<img width="648" alt="Screenshot 2020-11-13 at 16 40 55" src="https://user-images.githubusercontent.com/18049710/99079009-5f772080-25d0-11eb-9d48-c6ee989ed487.png">
<img width="652" alt="Screenshot 2020-11-13 at 16 41 25" src="https://user-images.githubusercontent.com/18049710/99079015-6140e400-25d0-11eb-8726-e1346de0a6fa.png">

Here we need to provide identity.
We can either:
1) Export Admin identity files from Vault page (available on dev). You need to go to vault, find identity by the issuer (currently they are named after the network) and export this identity. In future there will not be many of them as usually organizations will have only 2 issuers - cryptogen + fabric ca. When you export identity, you will get zip file. There is a directory `msp` inside it. You need to use `msp/signcerts/xxx.pem` as a public certificate and `msp/keystore/xx_priv` as a private key.
2) You can export admin identity json file from node details and use it in VS code extension. We aren't going to expose it in vault for now, we need to think if it useful, if we anyway expose identity files itself.
3) There is also an option for fabric CA to automatically enroll identity. Maybe in future we will somehow support it, but not now.
<img width="640" alt="Screenshot 2020-11-13 at 16 42 05" src="https://user-images.githubusercontent.com/18049710/99079020-62721100-25d0-11eb-9c7d-d42c5a214fc3.png">
As a result, we can see peer and channels that peer has joined. Additionally (as I understand) we can add built chaincode to the top panel and deploy to a connected peer (I tried but it didn't work, maybe I did smth wrong).
<img width="550" alt="Screenshot 2020-11-13 at 16 46 12" src="https://user-images.githubusercontent.com/18049710/99079024-643bd480-25d0-11eb-88aa-a0e86a85ba6d.png">

Additionally, you can add **gateway**. But, tbh, I didn't understand what it gives.
1) Export connection-profile
2) Add gateway specifying downloaded connection profile
<img width="654" alt="Screenshot 2020-11-13 at 16 46 31" src="https://user-images.githubusercontent.com/18049710/99080196-027c6a00-25d2-11eb-88f5-4ed1ca9e36f4.png">
<img width="630" alt="Screenshot 2020-11-13 at 16 47 07" src="https://user-images.githubusercontent.com/18049710/99080206-060ff100-25d2-11eb-9997-90f3a66faad0.png">
<img width="546" alt="Screenshot 2020-11-13 at 16 47 52" src="https://user-images.githubusercontent.com/18049710/99080219-0d36ff00-25d2-11eb-840f-240d79e39a60.png">


I suppose we should wait until they make a final release
