### ISSUE TITLE
Add a short guide how to configure Portis with Chainstack

### ISSUE THREAD

**Issue by easeev** [chainstack/docs#192]
https://docs.portis.io/#/configuration?id=network

**Comment by akegaviar** [comment]
Can't make it work. See [Portis issue](https://github.com/portis-project/web-sdk/issues/51).

**Comment by tomteman** [comment]
Hi @akegaviar , did you manage to overcome your issue? I'd be happy to help!

**Comment by akegaviar** [comment]
Thanks a lot @tomteman ! Looking into it, should be fine.

Appreciate your help!

**Comment by akegaviar** [comment]
Portis doesn't support basic auth.

**Comment by tomteman** [comment]
@akegaviar what do you mean by "basic auth"?

**Comment by akegaviar** [comment]
@tomteman I think I talked to you in your telegram group.

Basically, you don't support custom nodes that have RPC endpoints with `https://user-name:pass-word.nodehost.com`
