### ISSUE TITLE
Implement basic webApp for Hyperledger Fabric

### ISSUE THREAD

**Issue by ThomasRalee** [chainstack/docs#201]
### Background
- Create a basic web application (node.js and vue.js) for @akegaviar fabric [smart contract](https://github.com/akegaviar/freedomDividend)
- Deploy a fresh network on chainstack and link up to its connection profile
- Write a simple UI to communicate with the Fabric Network

### Additional Information
- Connection Profile Sample
```
{
  "name": "NW-935-951-4-profile",
  "description": "Profile for network NW-935-951-4",
  "version": "1.0.0",
  "channels": {
    "defaultchannel": {
      "orderers": [
        "nd-678-796-217.rg-254-409.int.chainstack.com"
      ],
      "peers": [
        "nd-886-443-961.rg-254-409.int.chainstack.com"
      ]
    }
  },
  "organizations": {
    "RG-254-409": {
      "mspid": "RG-254-409-MSP",
      "peers": [
        "nd-886-443-961.rg-254-409.int.chainstack.com"
      ]
    }
  },
  "orderers": {
    "nd-678-796-217.rg-254-409.int.chainstack.com": {
      "url": "grpcs://nd-678-796-217.rg-254-409.int.chainstack.com:7050",
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nMIICjjCCAjSgAwIBAgIRAOBseTArafw6OeCxOZHeNecwCgYIKoZIzj0EAwIwgZAx\nCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g\nRnJhbmNpc2NvMSYwJAYDVQQKEx1yZy0yNTQtNDA5LmludC5jaGFpbnN0YWNrLmNv\nbTEsMCoGA1UEAxMjdGxzY2EucmctMjU0LTQwOS5pbnQuY2hhaW5zdGFjay5jb20w\nHhcNMjAwMjI3MDcyNjAwWhcNMzAwMjI0MDcyNjAwWjCBkDELMAkGA1UEBhMCVVMx\nEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xJjAk\nBgNVBAoTHXJnLTI1NC00MDkuaW50LmNoYWluc3RhY2suY29tMSwwKgYDVQQDEyN0\nbHNjYS5yZy0yNTQtNDA5LmludC5jaGFpbnN0YWNrLmNvbTBZMBMGByqGSM49AgEG\nCCqGSM49AwEHA0IABLPdOQOhxrBf0ncvlVcMlV9SG8iCWyONYwABHeedfz8goRRo\n0AY2HqA49qbjDUfC38h3r7ZuxKBCMa72+RCt3lKjbTBrMA4GA1UdDwEB/wQEAwIB\npjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB\n/zApBgNVHQ4EIgQgSTrrbEHQ8q6RYYUDqKjAQTloNkqVtTRPmycLi4vrqmQwCgYI\nKoZIzj0EAwIDSAAwRQIhAPcON4pCRSv7FAyTuX2MH2SDcdy44TCQiR3BIaSlCy92\nAiB56NUrMJdvUbE9SdGe9L7+U4Ubnd0pxhqV9eu02ilvwA==\n-----END CERTIFICATE-----\n"
      }
    }
  },
  "peers": {
    "nd-886-443-961.rg-254-409.int.chainstack.com": {
      "url": "grpcs://nd-886-443-961.rg-254-409.int.chainstack.com:7051",
      "tlsCACerts": {
        "pem": "-----BEGIN CERTIFICATE-----\nMIICjjCCAjSgAwIBAgIRAKRTwUe4CiZNi70yyvfU7FowCgYIKoZIzj0EAwIwgZAx\nCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g\nRnJhbmNpc2NvMSYwJAYDVQQKEx1yZy0yNTQtNDA5LmludC5jaGFpbnN0YWNrLmNv\nbTEsMCoGA1UEAxMjdGxzY2EucmctMjU0LTQwOS5pbnQuY2hhaW5zdGFjay5jb20w\nHhcNMjAwMjI3MDcyNjAwWhcNMzAwMjI0MDcyNjAwWjCBkDELMAkGA1UEBhMCVVMx\nEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xJjAk\nBgNVBAoTHXJnLTI1NC00MDkuaW50LmNoYWluc3RhY2suY29tMSwwKgYDVQQDEyN0\nbHNjYS5yZy0yNTQtNDA5LmludC5jaGFpbnN0YWNrLmNvbTBZMBMGByqGSM49AgEG\nCCqGSM49AwEHA0IABKiSY54YCoDGsBNmr1Q0+giLsnjghQcn35bJKKpU4m9N4fhm\niV1hY7FUua3Mtnv3UVxm9vNsHC0YnH1LxLiu/umjbTBrMA4GA1UdDwEB/wQEAwIB\npjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB\n/zApBgNVHQ4EIgQgecrxnTaGNCqtwO8FcRJApHbJBh738oByXHKHy1WXWc4wCgYI\nKoZIzj0EAwIDSAAwRQIgSvomLTRasYJbWAV+iMWT6LFmCeQo2Z8Orf+mGISOAEkC\nIQCoY70LW0eTqPwze3h7Uxs9mLDEZVfWHrh5fu9mAy48AQ==\n-----END CERTIFICATE-----\n"
      }
    }
  }
}
```

**Comment by ThomasRalee** [comment]
#### Latest findings on this task:
- Spend quite some time working with hyperledger fabric sdk (nodejs) with a v2.0 fabric network created on Chainstack.
- Good news is that connecting to the network with `connection-profile` and `admin_identity` works
- Bad news is that the fabric sdk doesnt support the new v2.0 chaincode lifecycle
- Meaning i have to focus most of my effort next week on figuring out how to do this via node.js so that e2e can test chaincode operations

**Comment by easeev** [comment]
> * Bad news is that the fabric sdk doesnt support the new v2.0 chaincode lifecycle

Is there any ETA for support from the SDK developers?

**Comment by akegaviar** [comment]
> Is there any ETA for support from the SDK developers?

According to @jona-sc, they are not going to support it.

**Comment by jona-sc** [comment]
Seems it's supported in the Java SDK: https://github.com/hyperledger/fabric-sdk-java/blob/master/docs/release_v2.0.0_notes.md

**Comment by easeev** [comment]
As agreed, let's write a blog post describing the development lifecycle in Fabric 1.x vs 2.0 and create a simple application based on freedom dividend chaincode for the sake of it

**Comment by akegaviar** [comment]
[HLF 2.0 Node SDK Beta](https://github.com/hyperledger/fabric-sdk-node/blob/master/CHANGELOG.md#v200-beta4)

**Comment by ThomasRalee** [comment]
Going to get started with this TODAY

**Comment by ThomasRalee** [comment]
## Dapp is done and ready
#### Main page
   - display details via peer cli
   - peer lifecycle queryinstalled
   - peer lifecycle querycommitted
![image.png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/1c456ff9-b708-40ef-9c1e-cd07b0d52274)

#### Chaincode page
  - frontend chaincode interaction
![image.png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/665a5a1b-7e6e-4fff-9870-f08188cc2841)


## Todo:
- Convert tutorial base on **Single Org - Single Peer** Setup

**Comment by ThomasRalee** [comment]
need review => https://github.com/chainstack/freedom-dividend-chaincode/pull/4
