### ISSUE TITLE
CORS error when using deprecated HTTP provider in web3

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#215]
Create a KB article.

**Comment by easeev** [comment]
BTW the issue is not really with CORS but with the fact that basic auth credentials are not passed to the server so the request lands on "auth required" page which is not supposed to have any CORS policy

**Comment by akegaviar** [comment]
[Closed via KB](https://support.chainstack.com/hc/en-us/articles/900000587586-An-attempt-to-use-web3-js-errors-out-with-Request-has-been-blocked-by-CORS-policy-).
