### ISSUE TITLE
Ethereum full nodes are fast synced initially

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#223]
Add to docs/KB that our full Ethereum nodes were initially synced in fast sync mode.

Also look into [Limits of basic traces](https://github.com/ethereum/go-ethereum/wiki/Tracing:-Introduction#limits-of-basic-traces).

**Comment by easeev** [comment]
@akegaviar any updates on this?

**Comment by akegaviar** [comment]
https://support.chainstack.com/hc/en-us/articles/900001750726-Ethereum-nodes-are-fast-synced-initially
