### ISSUE TITLE
Documentation on bad programming practices for connecting to our nodes

### ISSUE THREAD

**Issue by kutysam** [chainstack/docs#259]
There was an issue with a customer making multiple connections to our nodes thus eventually making our node run out of ports.

The customer probably made a new connection for every call when the customer should have reused his connection for multiple calls.

The below call will result in 5 connections. [BAD]
```
from web3 import Web3
import time
for x in range(5):
    w3 = Web3(Web3.WebsocketProvider('wss://user:pass@nodeip.com'))
    print(w3.isConnected())
    #Do some ethereum command.
time.sleep(120)
```

The right approach would be to do 1 connection and then call that connection 5 times. Something like this.
This will only result in 1 connection.
```
from web3 import Web3
import time
w3 = Web3(Web3.WebsocketProvider('wss://user:pass@nodeip.com'))
for x in range(5):
    print(w3.isConnected())
    #Do some ethereum command.
time.sleep(120)
```

In order to prevent such port exhaustion issues, we need to educate the users on practices such as the above. We will have to do up a KB on such practices.

**Comment by akegaviar** [comment]
https://support.chainstack.com/hc/en-us/articles/900001918763-WebSocket-connection-to-an-Ethereum-node
