### ISSUE TITLE
Add service nodes

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#262]
Add docs around service nodes.
Scrub existing docs for service nodes related changes.
Look into the nodes glossary entry.

**Comment by easeev** [comment]
Jona Smulders Cohen  20 minutes ago
BTW @Ake a nice addition to this service nodes story that is maybe worth mentioning in the docs is that you can now access the NMS url which shows all nodes on a map

**Comment by akegaviar** [comment]
PR #272
