### ISSUE TITLE
Navbar logo is not clickable

### ISSUE THREAD

**Issue by neewy** [chainstack/docs#285]
Can we please add a link to our website/console from Navbar logo? It just feels natural to navigate back from the docs to the app. See this for inspiration https://github.com/vuejs/vuepress/issues/891

**Comment by neewy** [comment]
Right now it's just our logo in a div container

![Screenshot 2020-09-09 at 08 53 11](https://user-images.githubusercontent.com/11841667/92559787-e844a980-f279-11ea-8eac-0edd8c121697.png)

**Comment by akegaviar** [comment]
You are talking [API reference docs](https://docs.chainstack.com/api/reference/).

The [docs one](https://docs.chainstack.com/) is clickable.

Please migrate this issue to https://github.com/chainstack/api.

**Comment by Alomer71** [comment]
😀😃

**Comment by akegaviar** [comment]
@neewy ?
