### ISSUE TITLE
Update KB and documentation to match new user flows for Identities and Identity Issuers (Fabric & Corda)

### ISSUE THREAD

**Issue by neewy** [chainstack/docs#290]
As we're going to migrate HLF Admin identities in Vault along with Cryptogen tool, we need to update the KB articles and Fabric tutorials, that explain or cover:

- Downloading MSP folder
- Getting access to Admin identity data
- Hyperledger Fabric network creation
- Adding a peer to Hyperledger Fabric network

With our new functionality we need to cover the following stories in our knowledge base:

- chainstack/ui#2098 Deploy a Chainstack CA
- chainstack/ui#2091 Display a list of identity issuers in Chainstack vault
- chainstack/ui#2096 Show deployed Chainstack HLF CA in the list of Identity issuers 
- chainstack/ui#2073 Make legacy HLF Identity issuers visible in Vault IdP list
chainstack/ui#2074 Make legacy HLF Admin identities visible in Vault
- chainstack/ui#2093 Show Corda CAs in the list of identity issuers
- chainstack/ui#2094 Display details for a "legacy" Fabric CA service
- chainstack/ui#2095 Display details for Corda Network and Corda Pre-Production Network
- chainstack/ui#2111 Use Chainstack CA service during HLF network creation
- chainstack/ui#2107 Extend HLF network creation wizard with Identity Provider selection step
- chainstack/ui#2097 Display details for a deployed Chainstack CA service
- chainstack/ui#2103 Delete a legacy HLF CA
- chainstack/ui#2104 Delete a Chainstack CA
- chainstack/ui#2106 Delete an Admin or Client HLF identity
- chainstack/ui#2108 Display HLF identities & Issuers, associated with a Fabric network
- chainstack/ui#2115 Network creator adds new HLF peer to their network
- chainstack/ui#2109 Delete "legacy" identities from Fabric node details screen

**Comment by akegaviar** [comment]
?

**Comment by akegaviar** [comment]
@neewy need details please.

**Comment by akegaviar** [comment]
@neewy

**Comment by neewy** [comment]
@akegaviar apologies for leaving you hanging. We will cover first all the scope that relates to our HLF legacy migration. For Fabric CA service I'll create a separate docs ticket

**Comment by akegaviar** [comment]
@neewy can you please change the title too?
