### ISSUE TITLE
Research Task on TXPool / PendingTXFilter / PendingTXSubscription

### ISSUE THREAD

**Issue by kutysam** [chainstack/docs#303]
Things to research on and eventual insert to KB

- Difference between these approaches
- How they work in reality
- How they work if there's an account in wallet / if there's no account in the wallet and so on.
- Whether pendingTransactions returns only txs related to node's wallet (that it's supposed to) or not (since in Ake's test it returns other all txs)

Slack Thread: https://chainstackhq.slack.com/archives/CHK4Q7MMK/p1604791696000100

**Comment by kutysam** [comment]
Some current KB Articles:
- https://support.chainstack.com/hc/en-us/articles/900000820506-Checking-pending-and-queued-transactions-in-your-Ethereum-node-s-local-pool
- https://support.chainstack.com/hc/en-us/articles/900002863343-Filtering-new-global-pending-transactions
- https://support.chainstack.com/hc/en-us/articles/900003426246-Subscribing-to-global-new-pending-transactions

**Comment by kutysam** [comment]
Some things that I have identified.

## Mapping
1. Web3 maps its http calls to JSONRPC (For http calls)
- web3.eth.getPendingTransactions() --> Mapped To Geth `eth.pendingTransactions`

2. Web3 maps its websocket calls to geth methods 
- web3.eth.subscribe('pendingTransactions'..) --> Mapped to Geth `newPendingTransactions subscription`
- Take note that we cannot directly call a subscription using geth itself. We need to use websocket clients for this.

3. Web3 mapping to Geth [JSONRPC](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/src/index.js)

4. Geth mapping to methods(https://github.com/ethereum/go-ethereum/blob/master/internal/web3ext/web3ext.go)

I personally find it confusing that they have 'pendingTransactions' subscription which is actually mapped to 'newPendingTransactions' subscription for geth itself.
These are the other subscriptions geth supports https://geth.ethereum.org/docs/rpc/pubsub

## Viewing Local vs Global PENDING Transactions
### Local Transactions
1. [eth.pendingTransactions](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1702)

### Global Transactions
1. Subscribing to NewPendingTransactions [TXPool not enabled]
2. web3.eth.subscribe('pendingTransactions'..) [TXPool not enabled]
3. txpool.content - Also gives queued transactions [TXPool enabled]
4. GraphQL query - This puzzles me greatly because it gives almost all the details of txpool.content. However, txpool.inspect shows a slightly different variant. [TXPool not enabled]

## Filter, Subscribe, TXPool, GraphQL for pending transactions differences
### Filters
- Filter is done via JSONRPC, Subscribe is done via Websocket
- Once a filter is created, it will last for 5 minutes from the last poll.
1. There are two steps to a filter.
2. Create a filter and get the filterID
3. Paste the filterID to the getFilterMethod when you want to get the information.
4. The results will be from the last poll to current time.
- Anything before the filter time will not be shown.

### Subscribe
- Subscribe requires a constant active websocket connection
- Subscribe will stream all the data as they come in.
- Anything before the subscribe time will not be shown.

### [TX Pool](https://geth.ethereum.org/docs/rpc/ns-txpool)
- You can immediately get the GLOBAL pending transactions and queued transactions. (Size is about 3.5mb per response on mainnet)
- However, you do not get the full amount as it is limited to 4096 pending and 1024 queued transactions due to default command line geth settings.

### GraphQL
- This query can be ran WITHOUT txpool enabled. It will display out all the 4096 pending transaction. (No Queued transactions will be shown). Time taken is about the same with the txpool query base on my tests and its ~3.5MB too. The time can be cut down if we remove some unneeded information too.
```
query {
  pending {
    transactions {
      hash
      gas
      value
      gasPrice
      nonce
      r
      s
      v
      inputData
      status
      gasUsed
      cumulativeGasUsed
      from {
        address
      }
      to {
        address
      }
    }
  }
}
```

## Things I am unsure of
- I still can't find any JSONRPC command to display out ALL pendingtransactions without using txpool.
- Is it proper for graphql to display all pending transactions without txpool?

**Comment by neewy** [comment]
@kutysam Eugene suggested us to wrap this in a blog post

**Comment by CaJIbHuK** [comment]
Move to in progress because of the blog that will be prepared by @kutysam

**Comment by kutysam** [comment]
Forgot to update the link here: https://chainstack.sharepoint.com/:w:/r/teams/marketing/Shared%20Documents/Blog/Ethereum%20Pending%20Transactions.docx?d=w0b59efcf45474d88a0e657be24ccc8b3&csf=1&web=1&e=c2T0eP
