### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by ashliechin** [chainstack/docs#33]
There are several typos that exist in the new content found on the Chainstack docs. 

1. Under 'Application Development', the wrong article is each time a node is mentioned.

- Deploy *an* MultiChain node on Chainstack, and make a note of the connection details for the node.

- Deploy *an* Quorum node on Chainstack, and make a note of the connection details for the node.

2. Under 'Academic certificates on Ethereum

-"In this tutorial we will be writing *a* academic certificate generating DApp and will deploy it on public Ethereum node using Chainstack." This sentence structure feels odd in general. 

-This is an ownable contract. It is implemented in a way that only *authority* can generate a certificate and only the contract owner can transfer his authority. (is this correct? personally not sure- should it be *someone authorized*?)

- This is our main contract. It will handle *the* generation and verification of *certificates*.

- generates *a* certificate by calculating a hash of student name and details

3. In general, we are using the oxford comma in all our communications, which are missing in the new docs pages

**Comment by ashliechin** [comment]
@akegaviar

**Comment by akegaviar** [comment]
A fan of the Oxford comma myself, so I'm happy we'll be consistent in that across all our communications and docs.
