### ISSUE TITLE
Blogpost: Ethereum vs Polygon vs BSC DX

### ISSUE THREAD

**Issue by neewy** [chainstack/docs#349]

**Comment by ThomasRalee** [comment]
Take a look at the draft for the Blog post [here](https://chainstack.sharepoint.com/:w:/r/teams/marketing/_layouts/15/Doc.aspx?sourcedoc=%7B458d82df-fd48-4aba-8ca2-1f62d3715fbd%7D&action=edit&wdPid=5eb8638&cid=27ea18c9-495d-43fe-9ecc-0aaa34ef6906).

**Comment by ThomasRalee** [comment]
https://github.com/OffcierCia/DeFi-Developer-Road-Map
