### ISSUE TITLE
UI update for header and nav

### ISSUE THREAD

**Issue by mcbzz** [chainstack/docs#46]
## Summary
**Problem**
We do not have consistency in styling with the [Chainstack docs](https://docs.dev.chainstack.com/) site compared to the rest of the platform's header and side nav. 

**Solution**
Update the following items on the Docs site:
- Header logo, contents and colour
- Side navigation styling

### References
|Reference|Link|
|---|---|
|Designs| [Figma](https://www.figma.com/file/EAQn0HYOAdlkMaQXL6D3aWN1/docs?node-id=0%3A1)|

## Requirements
**Header**
1. Add the Chainstack Docs logo to the header
2. Update the styling for the search bar and 'try free' CTA
3. Add a link to the console
4. Review sizing and styling of the top header (incl. padding, borders, drop shadow, etc.)

**Side nav**
1. Change the background colour to light blue/grey
2. Remove borders
3. Change triangles to carets
4. Review spacing, sizing, and states (unselected, hover and selected)

**Comment by d2phap** [comment]
### Screenshots

![image](https://user-images.githubusercontent.com/3154213/63674352-ee0b5080-c818-11e9-9cbc-2ea840939352.png)


![image](https://user-images.githubusercontent.com/3154213/63674334-e350bb80-c818-11e9-987c-555ca157fbed.png)

![image](https://user-images.githubusercontent.com/3154213/63674457-2c087480-c819-11e9-8a7b-fd439b6a5aff.png)


![image](https://user-images.githubusercontent.com/3154213/63674504-417d9e80-c819-11e9-8c00-e00e7baeb2ab.png)


![image](https://user-images.githubusercontent.com/3154213/63674528-4b070680-c819-11e9-8903-86dddc9cd61e.png)

**Comment by hayorov** [comment]
Delivered to http://docs.dev.chainstack.com
