### ISSUE TITLE
Quorum w jupyter notebook

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#52]
https://github.com/hayorov/quorum-in-minutes-showcase/

**Comment by akegaviar** [comment]
Put it in Operations

**Comment by easeev** [comment]
1. Operations or tutorial is not a good fit IMO — Jupiter notebook is itself a "tutorial" format
2. Why don't we create a webinar based on this similar to https://www.wolfram.com/broadcast/video.php?c=463&v=2781?
