### ISSUE TITLE
Docs style guide 1.0.0

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#65]
Do and release version 1 of our documentation style guide

**Comment by akegaviar** [comment]
Moved this back while I focus on #34.

Expecting to return to this later this week.

**Comment by akegaviar** [comment]
I'll be offloading here my consistency notes in an unstructured manner and later compile in a doc. (This is for docs first and foremost).

emdashes in a sentence [CMOS style](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0114.html).

Bullet lists consistency (I'm in favor emdashes with spaces).

**Comment by akegaviar** [comment]
Clicking through UI elements is marked with `>`.

**Comment by akegaviar** [comment]
in-section H crosslinking must be done with a `#`.
eg `[word](#header)`.

cross-section H crosslinking is done with a `/path/section#header`.

cross-section section crosslinking is done with a `/path/section`.

**Comment by akegaviar** [comment]
Quotation marks punctuation — punctuation at the end of the sentence always goes inside the quotation marks. AmE style.

eg A sentence with a "quotation marks thingy."

**Comment by akegaviar** [comment]
Avoid one word linking, make sure you are linking a meaningful phrase that relates to the link.

Especially avoid using `click [here](link)`.

**Comment by akegaviar** [comment]
Pick one of the following formats and use it universally across docs:

`curl https://nd-123-456-789.p2pify.com -u "user-name:pass-word-pass-word-pass-word"`

OR

`curl https://user-name:pass-word-pass-word-pass-word@nd-123-456-789.p2pify.com`

**Comment by akegaviar** [comment]
use `id:1` for requests.

if the commands in a docs section, the ids should go:

1. step one
command: `id:1`

2. step two
smth else

3. step three
command: `id:2`

3. step three
command: `id:3`

If a request is independent, default to `id:1`:

Additional information
`id:1`

**Comment by akegaviar** [comment]
use (AmE): `Canceling`
do not use (BrE): `Cancelling`

use (AmE): `Canceled`
do not use (BrE): `Cancelled`

use (AmE/BrE): `Cancellation`
do not use (none): `Cancelation`

**Comment by akegaviar** [comment]
Use lowercase `ether` for currency. Not `ETH` or `Ether`.

**Comment by akegaviar** [comment]
[Chainstack account](link) should be for console.chainstack.com
[Chainstack](link) should be for chainstack.com.

**Comment by akegaviar** [comment]
Don't use "folder".
Use "directory".

**Comment by akegaviar** [comment]
Use `consortia` for consortium plural.

Both `consortia` & `consortiums` are accepted terms, with some dictionaries leaning towards `consortia`. That said, in the rare case that one has to use a possessive, then `consortia's` wins over `consortiums'`.

**Comment by akegaviar** [comment]
> Since Bitcoin is both a currency and a protocol, capitalization can be confusing. Accepted practice is to use Bitcoin (singular with an upper case letter B) to label the protocol, software, and community, and bitcoins (with a lower case b) to label units of the currency.

https://en.bitcoin.it/wiki/Help:Introduction#Capitalization_.2F_Nomenclature

Note that this is also in line with our use of `ether`:

> Use lowercase ether for currency. Not ETH or Ether.

**Comment by easeev** [comment]
Let's put this in https://github.com/chainstack/docs/wiki?

**Comment by akegaviar** [comment]
https://github.com/chainstack/docs/wiki/Documentation-style-guide
