### ISSUE TITLE
Update docs with Quorum API node creds instructions

### ISSUE THREAD

**Issue by akegaviar** [chainstack/docs#93]
Review the docs for Quorum nodes access and credentials and update the protected access instructions.

**Comment by akegaviar** [comment]
#268

**Comment by akegaviar** [comment]
Looks like 268 is done so I can start.

**Comment by easeev** [comment]
Depends on https://github.com/chainstack/core/issues/976

**Comment by akegaviar** [comment]
Partially fixed here https://github.com/chainstack/docs/commit/dd2512a50375164bc051e4bea404bbb18184f6ca

However it's blocked by #100
